### ISSUE TITLE
1080 to 720 Quality 

### ISSUE THREAD

**Issue by melbasuonyy** [yassineaddi/egybest-dl#8]
hello Thanks for the great work
I have question, when 1080 is not available i select 720 however it continues to grab 720 only for all episodes

is it possible to get 720 only for the missing episode then continue 720

![Screenshot 2022-01-02 011904](https://user-images.githubusercontent.com/29347988/147860431-feeff15f-368e-466f-8ca9-aa2a913b6de5.png)

**Comment by yassineaddi** [comment]
You're right that is what it's supposed to do, the issue should be fixed now, make sure to update the package using `pip install -U egybest-dl`. If you're still having problems, feel free to reopen this issue or create a new one.
